# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasketId', models.IntegerField(auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('Detail', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('Family', models.CharField(blank=True, max_length=30)),
                ('Credit', models.IntegerField(default=0)),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(max_length=200)),
                ('Rating', models.IntegerField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=30)),
                ('Discount', models.IntegerField(default=0)),
                ('TotalPrice', models.IntegerField(default=0)),
                ('Address', models.TextField(max_length=100)),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Basket')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=30)),
                ('Date', models.DateTimeField()),
                ('Amount', models.IntegerField(default=0)),
                ('Payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeoductOfBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=30)),
                ('Discount', models.IntegerField(default=0)),
                ('TotalPrice', models.IntegerField(default=0)),
                ('Address', models.TextField(max_length=100)),
                ('Date', models.DateField()),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Basket')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('Family', models.CharField(blank=True, max_length=30)),
                ('Price', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('Detail', models.TextField(max_length=200)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Category')),
            ],
        ),
        migrations.AddField(
            model_name='peoductofbasket',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
    ]
