# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Family',
        ),
    ]
