# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_remove_product_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOfBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='peoductofbasket',
            name='Basket',
        ),
        migrations.RemoveField(
            model_name='peoductofbasket',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='BasketId',
        ),
        migrations.AddField(
            model_name='basket',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeoductOfBasket',
        ),
        migrations.AddField(
            model_name='basket',
            name='ProductList',
            field=models.ManyToManyField(to='web.ProductOfBasket'),
        ),
    ]
