# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171114_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='Checkout',
            field=models.BooleanField(default=False),
        ),
    ]
