# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_basket_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='Basket',
        ),
        migrations.AddField(
            model_name='preorder',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorder',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
