# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171205_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
